version: "1.0"
info:
  model: int-scaffold
packages:
- name: SiqaGitTest0209Project
  gitServerName: kusiawsint1vc
  gitUrl: https://github.com/Rajni25Aug
  gitUsername: Rajni25Aug
  gitBranch: main
services:
- serviceName: project.siqagittest0209.integrations:debugtest
  packages:
  - name: SiqaGitTest0209Project
    version: "1.0"
- serviceName: pub.flow:debugLog
  packages:
  - name: WmPublic
    version: 11.1.0.0.2070
